dist: xenial
sudo: false
language: csharp
dotnet: 5.0.103
matrix:
  include:
    - mono: none
      env: DOTNETCORE=1
    - mono: latest
script:
  - git fetch --unshallow # in order to make Nerdbank.GitVersioning.Tasks.GetBuildVersion work
  - ./test-by-travis.sh
